spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ehgns
    username: root
    password: ${DB_PASSWORD}
  jwt:
    header: Authorization
    prefix: Bearer
    secret: "1123456789"
    accessExpiration: 271000
    refreshExpiration: 604800

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true